### ISSUE TITLE
Bad error handling for oauth errors

### ISSUE THREAD

**Issue by aaronkavlie-wf** [google/google-api-go-client#76] opened 2015-04-14 23:14 UTC
I got the following error on calls to `tableService.InsertAll().Do()`:

```
Post https://www.googleapis.com/bigquery/v2/projects/wf-aaronkavlie/datasets/test/tables/blank2/insertAll?alt=json: asn1: structure error: length too large
```

I eventually discovered that this was due to a `.pem` file I generated with the wrong `openssl` options.
The error message doesn't hint at the problem at all. It should be clear what failed, and why (even indicating that the problem was in authentication would help a lot).

**Comment by gmlewis** [comment] 2015-04-15 00:49
I believe I have seen this before with other APIs... and if I remember correctly, some payload wasn't base64 encoded when it should have been.  Also, the error message is coming from the JSON API endpoint server... not from google-api-go-client.  I'm not sure a whole lot can be done to help with this in the auto-generated library.  Leaving open for further investigation.

If you have a small, simple test case that reproduces the problem, that will dramatically help the speed with which I can investigate and debug this problem.

**Comment by aaronkavlie-wf** [comment] 2015-04-15 17:29
Steps to reproduce:

1. Set up an OAuth service account in Google dev console.
2. Download the `.p12` file
3. Generate the `.pem` file as follows (this is **not** the right way to do it, and the source of the problem):
```
openssl pkcs12 -in wf-aaronkavlie-97eb85083073.p12 -nocerts -out key.pem
```
4. Instantiate an oauth client for this Oauth account, using `"golang.org/x/oauth2/jwt"`.
5. Use the BigQuery client (`"google.golang.org/api/bigquery/v2"`) to attempt insertion into a table roughly as follows:

```go
bqClient, err := bigquery.New(oauthClient)
[put together jsonRows...]
request := &bigquery.TableDataInsertAllRequest{Rows: jsonRows}

tableService := bigquery.NewTabledataService(bq.client)
return tableService.InsertAll([project], [dataset], [table], request).Do()
```

**Comment by aaronkavlie-wf** [comment] 2015-04-15 17:41
@gmlewis let me know if you have any trouble reproducing based on the steps to reproduce above (which admittedly gloss over some details).

It may very well be that this can't be improved in the auto-generated library... in which case, it's one reason that auto-generated code isn't ideal (especially as the only option) for developers. I just reported here because this is where the issue surfaced.

**Comment by gmlewis** [comment] 2015-07-29 15:50
It looks like the error message from the BigQuery API has improved since the time that this bug was written.

Here is the error I get with bad `pem` data:
```
2015/07/29 08:41:13 GML: res=(*bigquery.TableDataInsertAllResponse)(nil), err=Post https://www.googleapis.com/bigquery/v2/projects/vm-gmlewis/datasets/mydataset/tables/mytable/insertAll?alt=json:
private key should be a PEM or plain PKSC1 or PKCS8;
parse error: asn1: structure error: length too large
```

For reference, here is the test program that I created:
```go
package main

import (
	"log"

	"golang.org/x/oauth2"
	"golang.org/x/oauth2/google"
	"golang.org/x/oauth2/jwt"
	bigquery "google.golang.org/api/bigquery/v2"
)

func main() {
	// Your credentials should be obtained from the Google
	// Developer Console (https://console.developers.google.com).
	conf := &jwt.Config{
		Email: "XXX@developer.gserviceaccount.com",
		// The contents of your RSA private key or your PEM file
		// that contains a private key.
		// If you have a p12 file instead, you
		// can use `openssl` to export the private key into a pem file.
		//
		//    $ openssl pkcs12 -in key.p12 -passin pass:notasecret -out key.pem -nodes
		//
		// The field only supports PEM containers with no passphrase.
		// The openssl command will convert p12 keys to passphrase-less PEM containers.
		PrivateKey: []byte(`-----BEGIN RSA PRIVATE KEY-----
...
-----END RSA PRIVATE KEY-----`),
		Scopes: []string{
			"https://www.googleapis.com/auth/bigquery",
		},
		TokenURL: google.JWTTokenURL,
		// If you would like to impersonate a user, you can
		// create a transport with a subject. The following GET
		// request will be made on the behalf of user@example.com.
		// Optional.
		// Subject: "user@example.com",
	}
	// Initiate an http.Client, the following GET request will be
	// authorized and authenticated on the behalf of user@example.com.
	client := conf.Client(oauth2.NoContext)
	// client.Get("...")

	bqClient, err := bigquery.New(client)
	// [put together jsonRows...]
	jsonRows := []*bigquery.TableDataInsertAllRequestRows{
		&bigquery.TableDataInsertAllRequestRows{
			Json: map[string]bigquery.JsonValue{
				"myfield": "value1",
			},
		},
	}
	request := &bigquery.TableDataInsertAllRequest{Rows: jsonRows}

	tableService := bigquery.NewTabledataService(bqClient)
	res, err := tableService.InsertAll("myproject", "mydataset", "mytable", request).Do()
	log.Printf("GML: res=%#v, err=%v", res, err)
	if res != nil {
		for _, v := range res.InsertErrors {
			log.Printf("GML: v=%#v", v)
			for _, e := range v.Errors {
				log.Printf("GML: e=%#v", e)
			}
		}
	}
}
```

Closing bug since it appears that the error message has improved.

**Closed by gmlewis** 2015-07-29 15:50 UTC
