### ISSUE TITLE
translate/v2 does not return the translation response

### ISSUE THREAD

**Issue by ronoaldo** [google/google-api-go-client#79] opened 2015-04-28 22:32 UTC
When you use the `translate/v2` package to translate text, the returned JSON payload wraps the "translations" array into a "data" attribute, as documented here: https://cloud.google.com/translate/v2/using_rest#Translate.

However, that attribute is not present in the response struct: TranslationsListResponse. This makes the decoded JSON attribute return an empty translations list.

Small test case:
```go
...
import "google.golang.org/api/translate/v2"

func TestTranslateApiCall(t testing.T) {
	...
	s, err := translate.New(oauthHttpClient)
	q := []string{"hello world"}
	resp, err := s.Translations.List(q, "es").Source("en").Do()
	if err != nil {
		t.Fatalf("Error making call to translate: %v", err)
	}
	// The payload is not decoded, but the call actually works
	// and receives the translation result
	if len(resp.Translations) != 1 {
		t.Errorf("Unexpected Translations length: %d, expected 1", len(resp.Translations))
	} else {
		if resp.Translations[0].TranslatedText != "hola mundo" {
			t.Errorf("Unexpected translation: %v", resp.Translations[0].TranslatedText)
		}
	}
}
```

**Comment by kmlx** [comment] 2015-06-11 17:46
yep, I confirm this is the case.

workaround:
```
type TranslationsListMain struct {
	// Data: main data structure; contains all other data
	Data *TranslationsListResponse `json:"data,omitempty"`
}
```
```
func (c *TranslationsListCall) Do() (*TranslationsListMain, error)
```
```
var ret *TranslationsListMain
```

**Comment by gmlewis** [comment] 2015-07-29 18:32
Update: having challenges authorizing test app to use the Translate API.  Getting weird error:
```
400. That’s an error.
Error: invalid_request
Missing required parameter: scope
```
Investigating.

**Comment by Wuvist** [comment] 2015-12-27 14:33
@gmlewis Translate API "does not have any methods that require OAuth 2.0 authorization, you might only need to obtain API keys" https://cloud.google.com/translate/v2/using_rest#auth

There is no need to wrap an oauth client, nor the "scope" exists in https://developers.google.com/identity/protocols/googlescopes

Using
```go
	httpClient := &http.Client{
		Transport: &transport.APIKey{Key: "API Key"},
	}
	svr, err := translate.New(httpClient)
```
is sufficient of using the API. Of cause, the  "data" attribute wrapper is also needed as mentioned by @ronoaldo

**Comment by eladg** [comment] 2016-03-05 14:24
@gmlewis / @Wuvist, you comments masked this ticket :confused: 

The translation api is still broken as originally reported. I've confirmed the request was actually performed (by reading the request body) yet Translations array is still empty (as originally reported).

**Comment by gmlewis** [comment] 2016-03-05 14:34
@eladg - I never said it wasn't broken. @Wuvist was suggesting a workaround. I need to get back to this one and investigate further.

**Comment by eladg** [comment] 2016-03-05 18:50
The problem is pretty simple:

```
elad:~/Desktop$ curl "https://www.googleapis.com/language/translate/v2?alt=json&key=<< API KEY >>&q=%D7%A9%D7%9C%D7%95%D7%9D&target=de"
{
 "data": {
  "translations": [
   {
    "translatedText": "Frieden",
    "detectedSourceLanguage": "iw"
   }
  ]
 }
}
```

While 
```golang
type TranslationsListResponse struct {
	Translations []*TranslationsResource `json:"translations,omitempty"`
	googleapi.ServerResponse `json:"-"`
	ForceSendFields []string `json:"-"`
}
```

@wuvist workaround is simply wrapping response code with `data`:
```golang
type TranslationsListMain struct {
    // Data: main data structure; contains all other data
    Data *TranslationsListResponse `json:"data,omitempty"`
}
```
And change Do to: `func (c *TranslationsListCall) Do() (*TranslationsListMain, error)`.

I would have submit a pull request but not sure how to contribute to the project (Sorry, not sure how to work with Gerrit and the rest of the google code-review tools)

**Comment by MDrollette** [comment] 2016-03-05 22:21
A similar problem was mentioned in #11

**Comment by eladg** [comment] 2016-03-10 06:50
Couldn't wait for a fix so patched it myself on eladg/google-api-go-client, too bad contributing to this repo is very challenging, yet I'm sure it's for the right reasons. Would be great seeing this fixed.

(anyhow, shameless promotion: github.com/eladg/tapi)

**Comment by Dynom** [comment] 2016-05-30 07:11
I'm curious why such a fundamental problem isn't patched yet, especially since we already have the solution right here. Everybody is now running with a locally patched `translate/v2` SDK. What's preventing the fix?

**Comment by mcgreevy** [comment] 2016-05-31 06:50
Sorry for the delay.  Because the data wrapper was an deprecated feature (https://developers.google.com/discovery/v1/using#discovery-features) affecting only a single API (the translate API), this issue was a lower priority than it would have been had it affected more APIs.  Thanks for your patience.  I've sent a fix for review (https://code-review.googlesource.com/#/c/4901/).  Once that's approved I'll be able to close this issue.

**Comment by Dynom** [comment] 2016-05-31 13:03
Alright @mcgreevy thanks, I'll update and test.

**Closed** 2016-06-01 00:42 UTC

**Comment by Dynom** [comment] 2016-06-01 07:29
Works like a charm, thanks for the update!
