### ISSUE TITLE
Missing id_token

### ISSUE THREAD

**Issue by ggitau** [google/google-api-go-client#91] opened 2015-07-31 07:41 UTC
I can't seem to get the id_token despite having set the scopes to email,profile. The token I get looks as shown below.

{"access_token":"xxxx","token_type":"Bearer","refresh_token":"xxxxx","expiry":"2015-07-31T11:30:34.916710314+03:00"}

**Comment by gmlewis** [comment] 2015-07-31 13:57
Can you please provide a small test case that reproduces the problem that you are seeing?

**Comment by deinspanjer** [comment] 2016-08-23 17:41
I was trying to do something similar, so I'll provide the example.

[example.zip](https://github.com/google/google-api-go-client/files/433168/example.zip)

If you run the python version, you'll see it can dump out the id_token that is needed for id verification by other applications.

If you run the go version twice which is cribbed very heavily from main.go, you'll see in the message about the cached token, there is no such id_token.

**Comment by jba** [comment] 2018-06-07 23:10
Closing due to age. If you're still experiencing a problem, please re-open.

**Closed by jba** 2018-06-07 23:10 UTC
Labels: type: question

**Comment by rolandjitsu** [comment] 2021-08-06 06:03
@jba Having the same issue, I cannot see the `id_token` in the userinfo payload:
```go
s, err := goauth.NewService(ctx, option.WithHTTPClient(c)) // is is an authenticated HTTP client - via access token
if err != nil {
	return err
}

uis := goauth.NewUserinfoV2MeService(s)
ui, err := uis.Get().Do()
if err != nil {
	return err
}
fmt.Println(ui)

token, err := s.Tokeninfo().Do()
if err != nil {
	return err
}

t, err := token.MarshalJSON()
if err != nil {
	return err
}
fmt.Println(string(t))
```
```
// Userinfo struct fields
&{....}
// JSON encoded token
{"audience":"someid.apps.googleusercontent.com","email":"my@email.com","expires_in":3600,"issued_to":"someid.apps.googleusercontent.com","scope":"openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile","user_id":"userid","verified_email":true}
```

But maybe I'm missing something?
